services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - certbot_certs:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    networks:
      - backend
    depends_on:
      - app
      - client
  certbot:
    image: certbot/certbot:v5.6.0
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  app:
    image: filimmon/market-analytics-server:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend

  client:
    image: filimmon/market-analytics-client:latest
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend
    ports:
      - '5432:5432'

volumes:
  postgres_data:
  certbot_certs:
  certbot_www:

networks:
  backend:
