services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
