services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '9894:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - app
      - client

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HTTP_DOMAIN=${HTTP_DOMAIN}
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=${HTTP_PORT}
      - NODE_ENV=${NODE_ENV}
      - HTTP_OPEN_API_PREFIX=${HTTP_OPEN_API_PREFIX}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRES=${JWT_ACCESS_EXPIRES}
      - JWT_REFRESH_EXPIRES=${JWT_REFRESH_EXPIRES}
      - RESEND_API_KEY=${RESEND_API_KEY}
    networks:
      - backend

  client:
    image: filimmon/market-analytics-client
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend
    ports:
      - '5432:5432'

volumes:
  postgres_data:

networks:
  backend:

# Арендовать vps. Закинуть по ssh и сбильдить на сервере
