export enum EPermissionCode {
  'PANEL_MARKETING_STRATEGY' = 'PANEL_MARKETING_STRATEGY',
  'PANEL_MARKETING_CHANNELS' = 'PANEL_MARKETING_CHANNELS',
  'PANEL_MARKETING_CHANNELS_PERFORMANCE' = 'PANEL_MARKETING_CHANNELS_PERFORMANCE',
  'PANEL_PROJECTS_DEVELOPER' = 'PANEL_PROJECTS_DEVELOPER',
  'PANEL_PROJECTS_API_KEYS' = 'PANEL_PROJECTS_API_KEYS',
  'PANEL_PROJECTS_USERS' = 'PANEL_PROJECTS_USERS',
  'PANEL_PROJECTS_ROLES' = 'PANEL_PROJECTS_ROLES',
  'PANEL' = 'PANEL',
  'PANEL_MARKETING' = 'PANEL_MARKETING',
  'PANEL_PROJECTS' = 'PANEL_PROJECTS',
}